sudo: required
addons:
  chrome: stable
language: node_js
node_js:
  - node
script:
  - npm run test_lib
  - npm run build_lib
before_deploy:
  - cd dist/ff-tooltip
deploy:
  provider: npm
  skip_cleanup: true
  email: developer@frontend-freelancer.com
  on:
    tags: true
    branch: master
